#from tkinter import *
#from tkinter import ttk 
#root = Tk()
#ttk.Button(root,text="Hello World").grid()
#root.mainloop()
from MMUFIFO import MMUFIFO
from FileProcessor import FileProcessor

new_mmu = MMUFIFO()
new_file_processor = FileProcessor()
new_file_processor.read_file_instructions('test.txt')
#new_mmu.print_something()
new_mmu.print_available_addresses()
new_mmu.process_new_command(1,40000)
new_mmu.print_memory_ussage()
new_mmu.print_available_addresses()
new_mmu.process_new_command(1,25000)
new_mmu.print_memory_ussage()
new_mmu.print_map()
new_mmu.print_queue()
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.process_new_command(2,25000)
new_mmu.print_map()
new_mmu.print_queue()
#new_mmu.process_use_command(1)
new_mmu.process_use_command(2)
new_mmu.print_map()
new_mmu.print_queue()
new_mmu.process_kill_command(1)
new_mmu.print_map()
new_mmu.print_queue()
new_mmu.print_available_addresses()
new_mmu.process_delete_command(3)
new_mmu.print_memory_ussage()
new_mmu.process_use_command(4)
new_mmu.print_memory_ussage()
print(new_mmu.get_ram_in_kb())
print(new_mmu.get_ram_in_percentage())
print(new_mmu.get_vram_in_kb())
print(new_mmu.get_vram_in_percentage())
print(new_mmu.clock)
print(new_mmu.get_trashing_time())
print(new_mmu.get_trashing_time_percentage())